package com.example.authenticationService.model;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import lombok.*;

import java.time.Instant;

import static com.example.authenticationService.common.constants.StringsGlobal.Auth.*;

@Entity
@Table(name = "users")

//Generated by Lombok (Boilerplate Shortcuts)
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class User {

    public enum UserStatus { PENDING, ACTIVE, SUSPENDED }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable = false)
    @NotBlank(message = SIGNUP_FNAME_REQ)
    private String firstName;

    @Column(nullable = false)
    @NotBlank(message = SIGNUP_LNAME_REQ)
    private String lastName;

    @Column(nullable = false, unique = true)
    @NotBlank(message = UNAME_REQUIRED)
    private String username;

    @Column(nullable = false, unique = true)
    @NotBlank(message = SIGNUP_EMAIL_REQ)
    private String email;

    @Column(nullable = false)
    @NotBlank(message = PASS_REQUIRED)
    private String password;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private UserStatus status = UserStatus.PENDING;

    @Column
    private Instant emailVerifiedAt;

    @Enumerated(EnumType.STRING)
    private AuthProvider provider;
}
